name = "SoftPosit"
uuid = "0775deef-a35f-56d7-82da-cfc52f91364d"
version = "0.5.0"

[deps]
SoftPosit_jll = "f9aa12f2-fb2a-5e38-99be-91dba0a1f972"

[compat]
SoftPosit_jll = "0.4.1, 0.4.2"
julia = "1.6, 1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
